language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_script:
  - pip install tox

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then tox -e py27; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then tox -e py34; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.5' ]]; then tox -e py35; fi
